spring.application.name=online-learning-new

spring.datasource.url=jdbc:mysql://mysql-3979-trietleminh7979-se181979.j.aivencloud.com:15995/online_learning_db?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_yVqLyB0YerxP07NWZVu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ClassRooms;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;characterEncoding=UTF-8;useUnicode=true
#spring.datasource.username=sa
#spring.datasource.password=12345
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA (?? nó t? t?o b?ng n?u ch?a có)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


# B?t bu?c dùng SSL v?i Aiven (quan tr?ng)
spring.datasource.properties.sslMode=REQUIRED

# C?u hình Cloudinary
cloudinary.cloud-name=drnufjdn2
cloudinary.api-key=523859565239349
cloudinary.api-secret=GTobs9wDPmbE2A-5NB67w3ua8fE
# --- C?U HÌNH UPLOAD FILE ---
# Cho phép upload file lên t?i 500MB (?? cho video bài gi?ng v?a ph?i)
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# T?t tính n?ng x? lý l??i bi?ng ?? b?t l?i file l?n s?m h?n
spring.servlet.multipart.resolve-lazily=true

gemini.api.key=${GEMINI_API_KEY}